config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'pages#home'
  get '/confidentiality', to: 'pages#confidentiality'
  get '/datauser', to: 'pages#datauser'


  resources :tv_shows, only: [:index, :show, :my] do
    resources :feedbacks, only: [:create, :update]
    resources :wishes, only: [:create]
  end


  resources :users, only: [:index, :show, :edit, :update] do
    member do
      post :follow
      post :unfollow
    end
  end

  resources :wishes, only: [:index, :destroy]

  namespace :my do
    resources :tv_shows, only: :index
  end

  namespace :swipe do
    resources :tv_shows, only: :index
  end

  namespace :search do
    resources :tv_shows, only: :index
  end

  namespace :search do
    resources :users, only: :index do
      member do
        post :follow
        post :unfollow
      end
    end
  end

  namespace :search do
    resources :followings, only: :index
  end

  namespace :search do
    resources :followers, only: :index
  end

  resources :watch_nows, only: [:index]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/search/followers_controller.rb
class Search::FollowersController < ApplicationController

  def index
    @users = current_user.followers
  end
end

app/controllers/search/followings_controller.rb
class Search::FollowingsController < ApplicationController

  def index
    @users = current_user.followings
  end
end

app/controllers/search/tv_shows_controller.rb
class Search::TvShowsController < ApplicationController
  def index
    if params[:query].present?
      sql_query = "title ILIKE :query OR genre ILIKE :query"
      if params[:filter].present?
        netflix_tv_shows = params[:filter]['netflix'] == '1' ? TvShow.where(sql_query, query: "%#{params[:query]}%").where(netflix: true) : []
        amazon_tv_shows = params[:filter]['amazon'] == '1' ? TvShow.where(sql_query, query: "%#{params[:query]}%").where(amazon: true) : []
        disney_tv_shows = params[:filter]['disney'] == '1' ? TvShow.where(sql_query, query: "%#{params[:query]}%").where(disney: true) : []
        ocs_tv_shows = params[:filter]['ocs'] == '1' ? TvShow.where(sql_query, query: "%#{params[:query]}%").where(ocs: true) : []
        canal_tv_shows = params[:filter]['canal'] == '1' ? TvShow.where(sql_query, query: "%#{params[:query]}%").where(canal: true) : []
        tv_shows_non_ordered = netflix_tv_shows + amazon_tv_shows + disney_tv_shows + ocs_tv_shows + canal_tv_shows
        @tv_shows = tv_shows_non_ordered.count.zero? ? TvShow.where(sql_query, query: "%#{params[:query]}%") : tv_shows_non_ordered.uniq.sort_by(&:id)
      else
        @tv_shows = TvShow.where(sql_query, query: "%#{params[:query]}%")
      end
    elsif params[:filter].present?
      netflix_tv_shows = params[:filter]['netflix'] == '1' ? TvShow.where(netflix: true) : []
      amazon_tv_shows = params[:filter]['amazon'] == '1' ? TvShow.where(amazon: true) : []
      disney_tv_shows = params[:filter]['disney'] == '1' ? TvShow.where(disney: true) : []
      ocs_tv_shows = params[:filter]['ocs'] == '1' ? TvShow.where(ocs: true) : []
      canal_tv_shows = params[:filter]['canal'] == '1' ? TvShow.where(canal: true) : []
      tv_shows_non_ordered = netflix_tv_shows + amazon_tv_shows + disney_tv_shows + ocs_tv_shows + canal_tv_shows
      @tv_shows = tv_shows_non_ordered.count.zero? ? TvShow.all : tv_shows_non_ordered.uniq.sort_by(&:id)
    else
      @tv_shows = TvShow.all
    end
  end
end

app/controllers/search/users_controller.rb
class Search::UsersController < ApplicationController
  before_action :set_user, only: [:follow, :unfollow]
  before_action :set_users, only: [:follow, :unfollow]
  before_action :set_origin, only: [:follow, :unfollow]


  def index
    if params[:query].present?
      sql_query = "last_name ILIKE :query OR first_name ILIKE :query"
      @users = User.where(sql_query, query: "%#{params[:query]}%")
    else
      @users = User.where.not(id: current_user).order(:first_name)
      ##@followings_ids = current_user.followings.pluck(:id)
      ##@users = current_user.followings.concat(User.where.not(id: @followings_ids))
    end
  end

  def follow
    if current_user.follow(@user.id)
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    end
  end

  def unfollow
    if current_user.unfollow(@user.id)
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js { render action: :follow }
      end
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def set_users
    case params[:origin]
    when "/search/users"
      puts "/search/users"
      @users = User.where.not(id: current_user).order(:first_name)
    when "/search/followings"
      puts "/search/followings"
      @users = current_user.followings
    when "/search/followers"
      puts "/search/followers"
      @users = current_user.followers
    else
      puts "He non"
    end
  end

  def set_origin
    @origin = params[:origin]
  end
end

app/views/search/followers/_follower.html.erb
<div>
  <div class="card-follows">
    <%=link_to user_path(follower) do %>
      <% if follower.facebook_picture_url.nil? %>
        <%= image_tag "avatar3.png"%>
      <% else %>
        <%= image_tag(follower.facebook_picture_url)%>
      <% end %>
      <div class="card-follows">
        <div class="card-follows-infos">
          <div class="card-follows-description">
            <h2><%= follower.first_name %> <%= follower.last_name %></h2>
          </div>

          <div class="follow">
            <% if follower == current_user %>
            <% elsif current_user.is_following?(follower.id) %>
              <%= link_to "Following", unfollow_search_user_path(follower.id), method: :post, remote: true, class: "following-button"%>
            <% else %>
              <%= link_to "Follow", follow_search_user_path(follower.id), method: :post, remote: true, class: "follow-button" %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/search/followers/index.html.erb
<div class="index-global-container-true">
  <div class="search-bar" id="search-bar-in-search">
      <%= form_tag search_tv_shows_path,class:"simple_form search", autocomplete:"off", method: :get do %>
        <div class="search-form-control form-group">
          <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Search"
          %>
          <button name="button" type="submit" class="btn btn-flat" id="search-btn">
            <i class="fa fa-search" id="search-icon"></i>
          </button>
        </div>
      <% end %>
  </div>
  <div class="tab-container">
  <ul class="list-inline tabs-underlined">
    <li>
      <a href="/search/tv_shows" class="tab-underlined">TV shows</a>
    </li>
    <li>
      <a href="/search/users" class="tab-underlined">Users</a>
    </li>
        <li>
      <a href="/search/followings" class="tab-underlined">Followings</a>
    </li>
    <li>
      <a href="/search/followers" class="tab-underlined activated">Followers</a>
    </li>
  </ul>
  </div>

  <div class="cards-follows">
    <%= render 'search/users/list', users: @users %>
  </div>
</div>