config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'pages#home'
  get '/confidentiality', to: 'pages#confidentiality'
  get '/datauser', to: 'pages#datauser'


  resources :tv_shows, only: [:index, :show, :my] do
    resources :feedbacks, only: [:create, :update]
    resources :wishes, only: [:create]
  end


  resources :users, only: [:index, :show, :edit, :update] do
    member do
      post :follow
      post :unfollow
    end
  end

  resources :wishes, only: [:index, :destroy]

  namespace :my do
    resources :tv_shows, only: :index
  end

  namespace :swipe do
    resources :tv_shows, only: :index
  end

  namespace :search do
    resources :tv_shows, only: :index
  end

  namespace :search do
    resources :users, only: :index do
      member do
        post :follow
        post :unfollow
      end
    end
  end

  namespace :search do
    resources :followings, only: :index
  end

  namespace :search do
    resources :followers, only: :index
  end

  resources :watch_nows, only: [:index]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  has_many :follower_relationships, foreign_key: :following_id, class_name: 'Follow'
  has_many :followers, through: :follower_relationships, source: :follower

  has_many :following_relationships, foreign_key: :follower_id, class_name: 'Follow'
  has_many :followings, through: :following_relationships, source: :following

  has_many :feedbacks, dependent: :destroy
  has_many :wishes, dependent: :destroy

  def self.find_for_facebook_oauth(auth)
    user_params = auth.slice("provider", "uid")
    user_params.merge! auth.info.slice("email", "first_name", "last_name")
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h

    user = User.find_by(provider: auth.provider, uid: auth.uid)
    user ||= User.find_by(email: auth.info.email) # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end

  def follow(user_id)
    following_relationships.create(following_id: user_id)
  end

  def suggestion(count=0)
    watched_ids = feedbacks.where.not(status: "unwatched").map(&:tv_show_id)
    superlike_follow_ids = followings.map { |user| user.feedbacks.where(status: "Superlike").map(&:tv_show_id) }.flatten
    result = superlike_follow_ids - watched_ids
    id = result.tally.sort_by(&:last).reverse[count].first
    TvShow.find(id)
  end

  def superliked_by
    tv_show = suggestion
    followings.select { |user| user.feedbacks.where(status: "Superlike", tv_show_id: tv_show.id) }
  end

  def suggestions_count
    watched_ids = feedbacks.where.not(status: "unwatched").map(&:tv_show_id)
    superlike_follow_ids = followings.map { |user| user.feedbacks.where(status: "Superlike").map(&:tv_show_id) }.flatten
    result = superlike_follow_ids - watched_ids
    result.tally.sort_by(&:last).reverse.size
  end

  def unfollow(user_id)
    following_relationships.find_by(following_id: user_id).destroy
  end

  def is_following?(user_id)
    relationship = Follow.find_by(follower_id: id, following_id: user_id)
    return true if relationship
  end

end

app/controllers/search/users_controller.rb
class Search::UsersController < ApplicationController
  before_action :set_user, only: [:follow, :unfollow]
  before_action :set_users, only: [:follow, :unfollow]
  before_action :set_origin, only: [:follow, :unfollow]


  def index
    if params[:query].present?
      sql_query = "last_name ILIKE :query OR first_name ILIKE :query"
      @users = User.where(sql_query, query: "%#{params[:query]}%")
    else
      @users = User.where.not(id: current_user).order(:first_name)
      ##@followings_ids = current_user.followings.pluck(:id)
      ##@users = current_user.followings.concat(User.where.not(id: @followings_ids))
    end
  end

  def follow
    if current_user.follow(@user.id)
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    end
  end

  def unfollow
    if current_user.unfollow(@user.id)
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js { render action: :follow }
      end
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def set_users
    case params[:origin]
    when "/search/users"
      puts "/search/users"
      @users = User.where.not(id: current_user).order(:first_name)
    when "/search/followings"
      puts "/search/followings"
      @users = current_user.followings
    when "/search/followers"
      puts "/search/followers"
      @users = current_user.followers
    else
      puts "He non"
    end
  end

  def set_origin
    @origin = params[:origin]
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])
    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:follow, :unfollow]

  def index
    @users = User.all
    @users = User.where.not(id: current_user)
  end

  def show
    @user = User.find(params[:id])
    @followings = Follow.where(follower: @user)
    @followers = Follow.where(following: @user)
    @feedbacks = @user.feedbacks.order(created_at: :desc)
    @superlikes = @user.feedbacks.where(status: "Superlike")
    @likes = @user.feedbacks.where(status: "Like")
    @dislikes = @user.feedbacks.where(status: "Dislike")
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(current_user)
  end

  def follow
    if current_user.follow(@user.id)
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    end
  end

  def unfollow
    if current_user.unfollow(@user.id)
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js { render action: :follow }
      end
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :description)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/views/users/_btnfollow.html.erb
<% if @user == current_user %>
    <%= link_to 'Edit my profile', edit_user_path(current_user), class: "btn btn-edit"%>
<% elsif current_user.is_following?(@user.id) %>
  <%= link_to "Following", unfollow_user_path(@user.id), method: :post, remote: true, class: "following-button"%>
<% else %>
  <%= link_to "Follow", follow_user_path(@user.id), method: :post, remote: true, class: "follow-button" %>
<% end %>

app/views/users/edit.html.erb
<div class="calque">
<div class="form-container-edit">
<%= simple_form_for [@user] do |f| %>
<%= f.input :first_name  %>
<br>
<%= f.input :last_name %>
<br>
<%= f.input :description %>
<br>
<%= f.button :submit, class:"btn btn-edit"%>
<% end %>
</div>
</div>

app/views/users/follow.js.erb
var btn = document.querySelector("#user-follow")
btn.innerHTML = "<%= j render "btnfollow" %>"

app/views/users/show.html.erb
<% content_for :meta_title, "#{DEFAULT_META["meta_product_name"]} | #{@user.first_name} #{@user.last_name}" %>
<% content_for :meta_description, "#{@user.first_name} #{@user.last_name} is on Sitcom" %>
<% if @user.facebook_picture_url.nil? %>
  <% content_for :meta_image, cl_image_path("https://icon-library.com/images/default-user-icon/default-user-icon-13.jpg") %>
<% else %>
  <% content_for :meta_image, cl_image_path(@user.facebook_picture_url) %>
<% end %>


<div>
  <div class="card-user px-3 my-3">
​
  <div class="user-header d-flex d-inline justify-content-between align-items-center my-2">
    <div class='mx-2'>
      <% if @user.facebook_picture_url.nil? %>
        <%= image_tag("https://icon-library.com/images/default-user-icon/default-user-icon-13.jpg", :class => "avatar-xlarge") %>
      <% else %>
        <%= image_tag(@user.facebook_picture_url, :class => "avatar-xlarge") %>
      <% end %>
    </div>
​
    <div class=' mx-2 align-items-center'>
      <div class="user-header-info text-center"><%= @user.feedbacks.count %></div>
      <p class = "mb-0">watched</p>
    </div>

    <%= link_to search_followings_path , class: "mx-2 align-items-center" do %>
      <div class="user-header-info text-center"><%= @followings.count %></div>
      <p class = "mb-0">followings</p>
    <% end %>

    <%= link_to search_followers_path, class:"mx-2 align-items-center" do %>
        <div class="user-header-info text-center"><%= @followers.count %></div>
        <p class = "mb-0">followers</p>
      </div>
    <% end %>

    <div>
      <h2 class="user-description mb-0"><%= @user.first_name %> <%= @user.last_name %></h2>
      <% if @user.id == current_user %>
        <p class="my-2"><%= @user.description %></p>
      <% end %>
    </div>

    <div class="btn-follow my-2" id="user-follow">
      <%= render "users/btnfollow"%>

    </div>
    <div>
      <% if @superlikes.count != 0 %>
        <div>
          <h5><%= @user.first_name %>'s Superlikes list</h5>
        </div>
      <% end %>
      <div class="index-cards-container">
        <% @feedbacks.each do |feedback| %>
          <% if feedback.status == "Superlike" %>
            <%= link_to tv_show_path(feedback.tv_show) do %>
              <div class="card-tv-show-poster">
                <div class="tv-show-poster">
                  <%= image_tag(feedback.tv_show.poster_url) %>
                </div>
              </div>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
​
    <div>
      <% if  @likes.count != 0  %>
        <div>
          <h5><%= @user.first_name %>'s Likes list</h5>
        </div>
      <% end %>
      <div class="index-cards-container">
        <% @feedbacks.each do |feedback| %>
          <% if feedback.status == "Like" %>
            <%= link_to tv_show_path(feedback.tv_show) do %>
              <div class="card-tv-show-poster">
                <div class="tv-show-poster">
                  <%= image_tag(feedback.tv_show.poster_url) %>
                </div>
              </div>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
​
    <div>
      <% if @dislikes.count != 0  %>
        <div>
          <h5><%= @user.first_name %>'s Dislikes list</h5>
        </div>
      <% end %>
      <div class="index-cards-container">
        <% @feedbacks.each do |feedback| %>
          <% if feedback.status == "Dislike" %>
            <%= link_to tv_show_path(feedback.tv_show) do %>
              <div class="card-tv-show-poster">
                <div class="tv-show-poster">
                  <%= image_tag(feedback.tv_show.poster_url) %>
                </div>
              </div>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
​
    <div>
      <h4>Activity</h4>
​
      <% @feedbacks.each do |feedback| %>
        <div class = "review-card px-3 d-flex align-items-center">
          <% if feedback.status == "Dislike" %>
            <p class="mb-0 py-2"><%=  @user.first_name %> <i class="fa fa-thumbs-o-down px-2" aria-hidden="true"></i> <%= feedback.tv_show.title%> <span class="feedback-time px-2"><%= time_ago_in_words(feedback.updated_at) %></span></p>
          <% elsif feedback.status == "Like" %>
            <p class="mb-0 py-2"><%=  @user.first_name %>  <i class="fa fa-thumbs-o-up px-2" aria-hidden="true"></i> <%= feedback.tv_show.title%> <span class="feedback-time px-2"><%= time_ago_in_words(feedback.created_at) %></span></p>
          <% elsif feedback.status == "Superlike" %>
            <p class="mb-0 py-2"><%=  @user.first_name %>  <i class="fa fa-heart px-2" aria-hidden="true"></i> <%= feedback.tv_show.title%> <span class="feedback-time px-2"><%= time_ago_in_words(feedback.created_at) %></span></p>
          <% end %>
        </div>
        <% if feedback.comment %>
          <div class = "review-card px-3">
            <p class="my-2"><%=  @user.first_name %> gave feedback on <%= feedback.tv_show.title%></p>
            <div class = "card-mini-tvshow d-flex d-inline">
              <%= image_tag(feedback.tv_show.poster_url, style: 'height:100%; width:20%') %>
              <div class = "px-3">
                <p class = "mb-0"><%= feedback.tv_show.title%></p>
                <p class = "mb-0">directed by <%= feedback.tv_show.director %></p>
                <p class = "mb-0"><%= feedback.rating %></p>
              </div>
            </div>
            <p class="mt-3 mb-0"><%= feedback.comment %></p>
            <p class="feedback-time"><%= time_ago_in_words(feedback.created_at) %></p>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/unfollow.js.erb
var btn = document.querySelector("#user-follow")
btn.innerHTML = "<%= j render "btnfollow" %>"