config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'pages#home'
  get '/confidentiality', to: 'pages#confidentiality'
  get '/datauser', to: 'pages#datauser'


  resources :tv_shows, only: [:index, :show, :my] do
    resources :feedbacks, only: [:create, :update]
    resources :wishes, only: [:create]
  end


  resources :users, only: [:index, :show, :edit, :update] do
    member do
      post :follow
      post :unfollow
    end
  end

  resources :wishes, only: [:index, :destroy]

  namespace :my do
    resources :tv_shows, only: :index
  end

  namespace :swipe do
    resources :tv_shows, only: :index
  end

  namespace :search do
    resources :tv_shows, only: :index
  end

  namespace :search do
    resources :users, only: :index do
      member do
        post :follow
        post :unfollow
      end
    end
  end

  namespace :search do
    resources :followings, only: :index
  end

  namespace :search do
    resources :followers, only: :index
  end

  resources :watch_nows, only: [:index]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_buttons-verification.html.erb
<% if Feedback.where(user_id: current_user, tv_show_id: @tv_show.id).empty? %>
  <div class="js-interact btn-interaction dislike", data-votes-target="dislikebtn">
    <%= link_to tv_show_feedbacks_path(feedback: {status: "Dislike"}, tv_show_id: @tv_show.id), remote: true, method: :post do %>
      <i class="fa fa-thumbs-down" id="thumb-down"></i>
    <% end %>
  </div>
  <div class="js-interact btn-interaction", data-votes-target="likebtn",>
    <%= link_to tv_show_feedbacks_path(feedback: {status: "Like"}, tv_show_id: @tv_show.id), remote: true, method: :post do %>
        <i class="fa fa-thumbs-up" id="thumb-up"></i>
    <% end %>
  </div>
  <div class="js-interact btn-interaction-superlike", data-votes-target="superlikebtn">
    <%= link_to tv_show_feedbacks_path(feedback: {status: "Superlike"}, tv_show_id: @tv_show.id), remote: true, method: :post do %>
      <i class="fa fa-heart" id="heart-like"></i>
    <% end %>
  </div>
<% else %>
  <% feedback = Feedback.where(user_id: current_user, tv_show_id: @tv_show.id).last %>
  <% status = Feedback.where(user_id: current_user, tv_show_id: @tv_show.id).last[:status] %>
  <% if status == "Like" %>
    <div class="js-interact btn-interaction dislike", data-votes-target="dislikebtn">
      <%= link_to tv_show_feedback_path(id: feedback.id, status: "Dislike", tv_show_id: @tv_show.id), remote: true, method: :patch do %>
        <i class="fa fa-thumbs-down" id="thumb-down"></i>
      <% end %>
    </div>
    <div class="js-interact btn-interaction active", data-votes-target="likebtn",>
      <%= link_to tv_show_feedback_path(id: feedback.id, status: "Like", tv_show_id: @tv_show.id), remote: true, method: :patch do %>
          <i class="fa fa-thumbs-up" id="thumb-up"></i>
      <% end %>
    </div>
    <div class="js-interact btn-interaction-superlike", data-votes-target="superlikebtn">
      <%= link_to tv_show_feedback_path(id: feedback.id, status: "Superlike", tv_show_id: @tv_show.id), remote: true, method: :patch do %>
        <i class="fa fa-heart" id="heart-like"></i>
      <% end %>
    </div>
  <% elsif status == "Dislike" %>
    <div class="js-interact btn-interaction dislike active", data-votes-target="dislikebtn">
      <%= link_to tv_show_feedback_path(id: feedback.id, status: "Dislike", tv_show_id: @tv_show.id), remote: true, method: :patch do %>
        <i class="fa fa-thumbs-down" id="thumb-down"></i>
      <% end %>
    </div>
    <div class="js-interact btn-interaction", data-votes-target="likebtn",>
      <%= link_to tv_show_feedback_path(id: feedback.id, status: "Like", tv_show_id: @tv_show.id), remote: true, method: :patch do %>
          <i class="fa fa-thumbs-up" id="thumb-up"></i>
      <% end %>
    </div>
    <div class="js-interact btn-interaction-superlike", data-votes-target="superlikebtn">
      <%= link_to tv_show_feedback_path(id: feedback.id, status: "Superlike", tv_show_id: @tv_show.id), remote: true, method: :patch do %>
        <i class="fa fa-heart" id="heart-like"></i>
      <% end %>
   </div>
  <% elsif status == "Dislike" %>
    <div class="js-interact btn-interaction dislike", data-votes-target="dislikebtn">
      <%= link_to tv_show_feedback_path(id: feedback.id, status: "Dislike", tv_show_id: @tv_show.id), remote: true, method: :patch do %>
        <i class="fa fa-thumbs-down" id="thumb-down"></i>
      <% end %>
    </div>
    <div class="js-interact btn-interaction", data-votes-target="likebtn",>
      <%= link_to tv_show_feedback_path(id: feedback.id, status: "Like", tv_show_id: @tv_show.id), remote: true, method: :patch do %>
          <i class="fa fa-thumbs-up" id="thumb-up"></i>
      <% end %>
    </div>
    <div class="js-interact btn-interaction-superlike active", data-votes-target="superlikebtn">
      <%= link_to tv_show_feedback_path(id: feedback.id, status: "Superlike", tv_show_id: @tv_show.id), remote: true, method: :patch do %>
        <i class="fa fa-heart" id="heart-like"></i>
      <% end %>
    </div>
  <% else %>
    <div class="js-interact btn-interaction dislike", data-votes-target="dislikebtn">
      <%= link_to tv_show_feedback_path(id: feedback.id, status: "Dislike", tv_show_id: @tv_show.id), remote: true, method: :patch do %>
        <i class="fa fa-thumbs-down" id="thumb-down"></i>
      <% end %>
    </div>
    <div class="js-interact btn-interaction", data-votes-target="likebtn",>
      <%= link_to tv_show_feedback_path(id: feedback.id, status: "Like", tv_show_id: @tv_show.id), remote: true, method: :patch do %>
          <i class="fa fa-thumbs-up" id="thumb-up"></i>
      <% end %>
    </div>
    <div class="js-interact btn-interaction-superlike", data-votes-target="superlikebtn">
      <%= link_to tv_show_feedback_path(id: feedback.id, status: "Superlike", tv_show_id: @tv_show.id), remote: true, method: :patch do %>
        <i class="fa fa-heart" id="heart-like"></i>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible alert-info-sitcom fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible alert-info-sitcom fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/SidneyOuarzazi/sitcom"><i class="fa fa-github"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
  </div>
  <div class="footer-logo">
    <%= image_tag "logo.png", class:"logo-footer"%>
  </div>
</div>

app/views/shared/_likes-votes-scores.html.erb
<div class="scores-number">
  <% if (((feedbacks_like_number.to_f + (feedbacks_superlike_number.to_f))/(feedbacks_like_number.to_f+feedbacks_superlike_number.to_f+feedbacks_dislike_number.to_f))*100).nan? %>
    <span>0</span>
  <% else %>
    <span><%= (((feedbacks_like_number.to_f + (feedbacks_superlike_number.to_f))/(feedbacks_like_number.to_f+feedbacks_superlike_number.to_f+feedbacks_dislike_number.to_f))*100).round %></span>
  <% end %>
  <span data-votes-target="superlikes", class="lineUp"><%= feedbacks_superlike_number = Feedback.where(tv_show_id: tv_show.id, status: "Superlike").count %></span>
  <span data-votes-target="likes">
    <% if feedbacks_like_number.nil? %>
      <%= 0 %>
    <% else %>
      <%= feedbacks_like_number %>
    <% end %>
  </span>
  <span data-votes-target="dislikes">
    <% if feedbacks_dislike_number.nil? %>
      <%= 0 %>
    <% else %>
      <%= feedbacks_dislike_number %>
    <% end %>
  </span>
</div>

app/views/shared/_likes_votes_scores.html.erb
<div class="scores-number">
  <% if (((feedbacks_like_number.to_f + (feedbacks_superlike_number.to_f))/(feedbacks_like_number.to_f+feedbacks_superlike_number.to_f+feedbacks_dislike_number.to_f))*100).nan? %>
    <span>0</span>
  <% else %>
    <span><%= (((feedbacks_like_number.to_f + (feedbacks_superlike_number.to_f))/(feedbacks_like_number.to_f+feedbacks_superlike_number.to_f+feedbacks_dislike_number.to_f))*100).round %></span>
  <% end %>
  <span data-votes-target="superlikes", class="lineUp"><%= feedbacks_superlike_number = Feedback.where(tv_show_id: tv_show.id, status: "Superlike").count %></span>
  <span data-votes-target="likes">
    <% if feedbacks_like_number.nil? %>
      <%= 0 %>
    <% else %>
      <%= feedbacks_like_number %>
    <% end %>
  </span>
  <span data-votes-target="dislikes">
    <% if feedbacks_dislike_number.nil? %>
      <%= 0 %>
    <% else %>
      <%= feedbacks_dislike_number %>
    <% end %>
  </span>
</div>

app/views/shared/_modal-facebook.html.erb
<div class="modal fade" id="facebookModal" tabindex="-1" aria-labelledby="facebookModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="form-sign-in px-4">
        <div class="form-sign-in-info d-flex flex-column justify-content-center text-center">
          <div>
            <h2 class="py-2">Log in</h2>
          </div>
          <div class="py-2">
            <%= render "devise/shared/links" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar <%= "navbar-fixed" if params[:action] == "show" %> navbar-expand-sm navbar-dark navbar-lewagon">
  <div class="container-fluid">
    <div id="home-logo">
      <%= link_to tv_shows_path, class:"navbar-brand" do %>
        <%= image_tag "logo.png", class: "logo"%>
      <% end %>
    </div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
      <% if !user_signed_in? %>
        <%= link_to "Login", new_user_session_path, class:"dropdown-item" %>
        <%= link_to "Register", new_user_registration_path, class:"dropdown-item" %>
      <% else %>
        <p><i class="fa fa-play"></i><%= link_to "Swipe", swipe_tv_shows_path, class:"dropdown-item" %></p>
        <p><i class="fa fa-user"></i><%= link_to "My profile", user_path(current_user), class:"dropdown-item" %></p>
        <p><i class="fa fa-star"></i><%= link_to "WishList", wishes_path, class:"dropdown-item" %></p>
        <p><i class="fa fa-users"></i><%= link_to "Users", search_users_path, class:"dropdown-item" %></p>
        <p><i class="fa fa-sign-out"></i><%= link_to "Log out", destroy_user_session_path, method: :delete, class:"dropdown-item"%></p>
      <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_votes_scores.html.erb
<div class="scores-number">
  <% if (((feedbacks_like_number.to_f + (feedbacks_superlike_number.to_f))/(feedbacks_like_number.to_f+feedbacks_superlike_number.to_f+feedbacks_dislike_number.to_f))*100).nan? %>
    <span>0</span>
  <% else %>
    <span><%= (((feedbacks_like_number.to_f + (feedbacks_superlike_number.to_f))/(feedbacks_like_number.to_f+feedbacks_superlike_number.to_f+feedbacks_dislike_number.to_f))*100).round %></span>
  <% end %>
  <span data-votes-target="superlikes", class="lineUp"><%= feedbacks_superlike_number = Feedback.where(tv_show_id: tv_show.id, status: "Superlike").count %></span>
  <span data-votes-target="likes">
    <% if feedbacks_like_number.nil? %>
      <%= 0 %>
    <% else %>
      <%= feedbacks_like_number %>
    <% end %>
  </span>
  <span data-votes-target="dislikes">
    <% if feedbacks_dislike_number.nil? %>
      <%= 0 %>
    <% else %>
      <%= feedbacks_dislike_number %>
    <% end %>
  </span>
</div>

app/views/shared/_wishlist-button.html.erb
<% if Wish.where(tv_show_id: @tv_show).map(&:user_id).include?(current_user.id)%>
  <i class="fa fa-heart" style="text-shadow: 0 0 8px #FFF;"></i>
<% else %>
  <i class="fa fa-heart-o" style="text-shadow: 0 0 8px #FFF;" ></i>
<% end %>