config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'pages#home'
  get '/confidentiality', to: 'pages#confidentiality'
  get '/datauser', to: 'pages#datauser'


  resources :tv_shows, only: [:index, :show, :my] do
    resources :feedbacks, only: [:create, :update]
    resources :wishes, only: [:create]
  end


  resources :users, only: [:index, :show, :edit, :update] do
    member do
      post :follow
      post :unfollow
    end
  end

  resources :wishes, only: [:index, :destroy]

  namespace :my do
    resources :tv_shows, only: :index
  end

  namespace :swipe do
    resources :tv_shows, only: :index
  end

  namespace :search do
    resources :tv_shows, only: :index
  end

  namespace :search do
    resources :users, only: :index do
      member do
        post :follow
        post :unfollow
      end
    end
  end

  namespace :search do
    resources :followings, only: :index
  end

  namespace :search do
    resources :followers, only: :index
  end

  resources :watch_nows, only: [:index]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/watch_nows_controller.rb
class WatchNowsController < ApplicationController
  def index
    count = 0
    if params[:count].present?
      count = params[:count].to_i
      #count 0 si on arrive à la fin
    end
    @suggestion = current_user.suggestion(count)
    @superliked_users = current_user.superliked_by
    if (count + 1) == current_user.suggestions_count
      @next_movie = 0
    else
      @next_movie = params[:count].to_i + 1
    end

  end
end

app/views/watch_nows/index.html.erb
<div class="card-suggestion">
  <h2 class="text-center title-suggest">Here is our suggestion!</h2>

  <div class="card-suggestion-info d-flex flex-column justify-content-center">
    <%= link_to tv_show_path(@suggestion) do %>
      <div class="card-suggestion-tvshow" style="text-align:center;">
        <div class="card-suggestion-tvshow-poster">
          <%= image_tag(@suggestion.poster_url) %>
        </div>
      </div>
    <% end %>

     <div class="card-purchase-score-suggest">
        <p class="px-2 mb-0"><%= @suggestion.popularity_score(current_user) %> <i class="fa fa-users mx-2"></i></p>
      </div>

    <div class="followers-superliked-container d-flex d-inline mx-5">
      <div class="users-pile-container">
      <div class="users-pile-avatar">
        <% @superliked_users.each do |user| %>
          <%= image_tag(user.facebook_picture_url, class: "avatar") %>
        <% end %>
      </div>
      </div>
      <div class="followers-seen-info px-2">
        <% string_follows = pluralize(@superliked_users.length - 1, "other") %>
        <% if @superliked_users.empty? %>
        <% elsif @superliked_users.length == 1 %>
          <%= "#{@superliked_users.last.first_name} has superliked it" %>
        <% else %>
          <%= "#{@superliked_users.last.first_name} and #{string_follows} have superliked it" %>
        <% end %>
      </div>
    </div>




    <div class="btn-again" style="text-align:center;">
      <%= link_to watch_nows_path(count: @next_movie) do %>
        <p class="btn btn-ghost play-btn my-3" style="width:50%;"><i class="fa fa-repeat mx-2" aria-hidden="true"></i>Again</p>
      <% end %>
    </div>
  </div>
</div>